/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FfxVUC9UhUJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
// export function QuizLayout() {

import { useState } from 'react';
import { BackgroundGradient } from './ui/background-gradient';

export function QuizLayout() {
  const [selectedAnswer, setSelectedAnswer] = useState('');
  const correctAnswer = 'Paris';

  const handleAnswerClick = (answer: string) => {
    setSelectedAnswer(answer);
  };

  return (
    <div>
      <BackgroundGradient className="rounded-[22px] max-w-sm p-4 sm:p-10 bg-white dark:bg-zinc-900">
        <div className="space-y-6">
          <h1 className="text-2xl font-bold">Quiz Question</h1>
          <p className="text-gray-400">What is the capital city of France?</p>
          <div className="space-y-4">
          <button
            disabled={!!selectedAnswer}
            className={`${
              selectedAnswer === 'Berlin' && selectedAnswer !== correctAnswer
                ? 'bg-red-500 border-red-500'
                : 'bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500'
            } rounded-md px-4 py-2 w-full text-left`}
            onClick={() => handleAnswerClick('Berlin')}
          >
            Berlin
          </button>
          <button
            disabled={!!selectedAnswer}
            className={`${
              selectedAnswer === 'Paris'
                ? 'bg-green-500 border-green-500'
                : 'bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500'
            } rounded-md px-4 py-2 w-full text-left`}
            onClick={() => handleAnswerClick('Paris')}
          >
            Paris
          </button>
          <button
            disabled={!!selectedAnswer}
            className={`${
              selectedAnswer === 'Madrid' && selectedAnswer !== correctAnswer
                ? 'bg-red-500 border-red-500'
                : 'bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500'
            } rounded-md px-4 py-2 w-full text-left`}
            onClick={() => handleAnswerClick('Madrid')}
          >
            Madrid
          </button>
          <button
          disabled={!!selectedAnswer}
            className={`${
              selectedAnswer === 'London' && selectedAnswer !== correctAnswer
                ? 'bg-red-500 border-red-500'
                : 'bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500'
            } rounded-md px-4 py-2 w-full text-left`}
            onClick={() => handleAnswerClick('London')}
          >
            London
          </button>
          </div>
        </div>
      </BackgroundGradient>
    </div>
  );
}

//   return (
//     <div className="flex items-center justify-center">
//       <div className="bg-gray-800 rounded-lg shadow-lg p-8 w-full max-w-md">
//         <div className="space-y-6">
//           <h1 className="text-2xl font-bold">Quiz Question</h1>
//           <p className="text-gray-400">What is the capital city of France?</p>
//           <div className="space-y-4">
//             <button className="bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500 rounded-md px-4 py-2 w-full text-left">
//               Paris
//             </button>
//             <button className="bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500 rounded-md px-4 py-2 w-full text-left">
//               London
//             </button>
//             <button className="bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500 rounded-md px-4 py-2 w-full text-left">
//               Berlin
//             </button>
//             <button className="bg-gray-700 hover:bg-gray-600 focus:ring focus:ring-gray-500 rounded-md px-4 py-2 w-full text-left">
//               Madrid
//             </button>
//           </div>
//         </div>
//       </div>
//     </div>
//   )
// }
